"""Declare all the fields & associated regexes you want for pulling info from NMSSMTools spectrum file"""


import re


class Field(object):
    def __init__(self, block, regex, name, type, comment):
        self.block = block
        self.regex = regex
        self.name = name
        self.type = type
        if comment == '' or comment is None:
          self.comment = regex.pattern.split('#')[1].replace('\\', '')
        else:
          self.comment = comment

    def __str__(self):
      return 'Field({0})'.format(self.__dict__)

    def __repr__(self):
      return 'Field({0})'.format(self.__dict__)


nmssmtools_fields = [
    # parameters
    Field(block='MINPAR', name="tgbeta", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# TANBETA\(MZ\)'),
          comment=''),
    Field(block='EXTPAR', name="mueff", type=float,
          regex=re.compile(r' +65 +([E\d\.\-\+]+) +\# MUEFF'),
          comment=''),
    Field(block='EXTPAR', name="lambda", type=float,
          regex=re.compile(r' +61 +([E\d\.\-\+]+) +\# LAMBDA'),
          comment=''),
    Field(block='EXTPAR', name="kappa", type=float,
          regex=re.compile(r' +62 +([E\d\.\-\+]+) +\# KAPPA'),
          comment=''),
    Field(block='EXTPAR', name="alambda", type=float,
          regex=re.compile(r' +63 +([E\d\.\-\+]+) +\# ALAMBDA'),
          comment=''),
    Field(block='EXTPAR', name="akappa", type=float,
          regex=re.compile(r' +64 +([E\d\.\-\+]+) +\# AKAPPA'),
          comment=''),

    # Field(block='EXTPAR', name="m0", type=float,
    #       regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# M0\(MGUT\)'),
    #       comment=''),
    # Field(block='EXTPAR', name="m12", type=float,
    #       regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# M12\(MGUT\)'),
    #       comment=''),
    # Field(block='EXTPAR', name="a0", type=float,
    #       regex=re.compile(r' +5 +([E\d\.\-\+]+) +\# A0\(MGUT\)'),
    #       comment=''),

    Field(block='EXTPAR', name="m3", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# M3'),
          comment=''),
    Field(block='EXTPAR', name="m2", type=float,
          regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# M2'),
          comment=''),
    Field(block='EXTPAR', name="m1", type=float,
          regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# M1'),
          comment=''),

    Field(block='EXTPAR', name="mu3", type=float,
          regex=re.compile(r' +46 +([E\d\.\-\+]+) +\# RIGHT T-SQUARKS'),
          comment=''),
    Field(block='EXTPAR', name="mu2", type=float,
          regex=re.compile(r' +45 +([E\d\.\-\+]+) +\# RIGHT C-SQUARKS'),
          comment=''),

    Field(block='EXTPAR', name="mq3", type=float,
          regex=re.compile(r' +43 +([E\d\.\-\+]+) +\# LEFT 3RD GEN. SQUARKS'),
          comment=''),
    Field(block='EXTPAR', name="mq2", type=float,
          regex=re.compile(r' +42 +([E\d\.\-\+]+) +\# LEFT 2ND GEN. SQUARKS'),
          comment=''),

    Field(block='EXTPAR', name="au3", type=float,
          regex=re.compile(r' +11 +([E\d\.\-\+]+) +\# ATOP'),
          comment=''),
    Field(block='EXTPAR', name="ad3", type=float,
          regex=re.compile(r' +12 +([E\d\.\-\+]+) +\# ABOTTOM'),
          comment=''),

    Field(block='EXTPAR', name="ml3", type=float,
          regex=re.compile(r' +33 +([E\d\.\-\+]+) +\# LEFT STAU'),
          comment=''),
    Field(block='EXTPAR', name="ml2", type=float,
          regex=re.compile(r' +32 +([E\d\.\-\+]+) +\# LEFT SMUON'),
          comment=''),

    Field(block='EXTPAR', name="me3", type=float,
          regex=re.compile(r' +36 +([E\d\.\-\+]+) +\# RIGHT STAU'),
          comment=''),
    Field(block='EXTPAR', name="me2", type=float,
          regex=re.compile(r' +35 +([E\d\.\-\+]+) +\# RIGHT SMUON'),
          comment=''),

    Field(block='EXTPAR', name="ae3", type=float,
          regex=re.compile(r' +13 +([E\d\.\-\+]+) +\# ATAU'),
          comment=''),
    Field(block='EXTPAR', name="ae2", type=float,
          regex=re.compile(r' +16 +([E\d\.\-\+]+) +\# AMUON'),
          comment=''),

    Field(block='EXTPAR', name="md3", type=float,
          regex=re.compile(r' +49 +([E\d\.\-\+]+) +\# RIGHT B-SQUARKS'),
          comment=''),
    Field(block='EXTPAR', name="md2", type=float,
          regex=re.compile(r' +48 +([E\d\.\-\+]+) +\# RIGHT S-SQUARKS'),
          comment=''),

    # masses
    Field(block='MASS', name="mh1", type=float,
          regex=re.compile(r' +25 +([E\d\.\-\+]+) +\# lightest neutral scalar'),
          comment=''),
    Field(block='MASS', name="mh2", type=float,
          regex=re.compile(r' +35 +([E\d\.\-\+]+) +\# second neutral scalar'),
          comment=''),
    Field(block='MASS', name="mh3", type=float,
          regex=re.compile(r' +45 +([E\d\.\-\+]+) +\# third neutral scalar'),
          comment=''),
    Field(block='MASS', name="ma1", type=float,
          regex=re.compile(r' +36 +([E\d\.\-\+]+) +\# lightest pseudoscalar'),
          comment=''),
    Field(block='MASS', name="ma2", type=float,
          regex=re.compile(r' +46 +([E\d\.\-\+]+) +\# second pseudoscalar'),
          comment=''),
    Field(block='MASS', name="mhc", type=float,
          regex=re.compile(r' +37 +([E\d\.\-\+]+) +\# charged Higgs'),
          comment=''),
    Field(block='MASS', name="mstop1", type=float,
          regex=re.compile(r'   1000006 +([E\d\.\-\+]+) +#  ~t_1'),
          comment=''),
    Field(block='MASS', name="mstop2", type=float,
          regex=re.compile(r'   2000006 +([E\d\.\-\+]+) +#  ~t_2'),
          comment=''),
    Field(block='MASS', name="msbottom1", type=float,
          regex=re.compile(r'   1000005 +([E\d\.\-\+]+) +#  ~b_1'),
          comment=''),
    Field(block='MASS', name="msbottom2", type=float,
          regex=re.compile(r'   2000005 +([E\d\.\-\+]+) +#  ~b_2'),
          comment=''),
    Field(block='MASS', name="mgluino", type=float,
          regex=re.compile(r'   1000021 +([E\d\.\-\+]+) +#  ~g'),
          comment=''),
    Field(block='MASS', name="mneutralino1", type=float,
          regex=re.compile(r'   1000022 +([E\d\.\-\+]+) +# neutralino\(1\)'),
          comment=''),
    Field(block='MASS', name="mneutralino2", type=float,
          regex=re.compile(r'   1000023 +([E\d\.\-\+]+) +# neutralino\(2\)'),
          comment=''),
    Field(block='MASS', name="mchargino1", type=float,
          regex=re.compile(r'   1000024 +([E\d\.\-\+]+) +# chargino\(1\)'),
          comment=''),

    # Flavour observeables
    Field(block="LOWEN", name="bsgamma", type=float,
          regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# BR\(b \-> s gamma\)'),
          comment=''),
    Field(block="LOWEN", name="delmd", type=float,
          regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# Delta M_d in ps\^\-1'),
          comment=''),
    Field(block="LOWEN", name="delms", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# Delta M_s in ps\^\-1'),
          comment=''),
    Field(block="LOWEN", name="bsmumu", type=float,
          regex=re.compile(r' +4 +([E\d\.\-\+]+) +\# BR\(Bs \-> mu\+mu\-\)'),
          comment=''),
    Field(block="LOWEN", name="btaunu", type=float,
          regex=re.compile(r' +5 +([E\d\.\-\+]+) +\# BR\(B\+ \-> tau\+ \+ nu_tau\)'),
          comment=''),
    # g-2
    Field(block='LOWEN', name="Del_a_mu", type=float,
          regex=re.compile(r' +6 +([E\d\.\-\+]+) +\# Del_a_mu'),
          comment=''),
    Field(block='LOWEN', name="omega", type=float,
          regex=re.compile(r' +10 +([E\d\.\-\+]+) +\# Omega h\^2'),
          comment=''),
    # b ->c tau nu
    Field(block='LOWEN', name="rd", type=float,
          regex=re.compile(r'# +([E\d\.\-\+]+) +RD'),
          comment='RD'),
    Field(block='LOWEN', name="rds", type=float,
          regex=re.compile(r'# +([E\d\.\-\+]+) +RD\*'),
          comment='RD*'),

    # Reduced Higgs Couplings Bosons
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h1ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +25 +21 +21 \# Higgs\(1\)-gluon-gluon reduced coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h1bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +25 +5 +5 \# Higgs\(1\)-b-b red\. coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h1vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +25 +24 +24 \# Higgs\(1\)-W-W reduced coupling\^2'),
          comment=''),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h2ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +35 +21 +21 \# Higgs\(2\)-gluon-gluon reduced coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h2bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +35 +5 +5 \# Higgs\(2\)-b-b red\. coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h2vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +35 +24 +24 \# Higgs\(2\)-W-W reduced coupling\^2'),
          comment=''),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h3ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +45 +21 +21 \# Higgs\(3\)-gluon-gluon reduced coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h3bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +45 +5 +5 \# Higgs\(3\)-b-b red\. coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h3vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +45 +24 +24 \# Higgs\(3\)-W-W reduced coupling\^2'),
          comment=''),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="a1ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +36 +21 +21 \# CP-odd Higgs\(1\)-gluon-gluon reduced coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="a1tautaurc2", type=float,
          regex=re.compile(r' +[E\d\.\-\+]+ +([E\d\.\-\+]+) +3 +36 +15 +15 \# CP-odd Higgs\(1\)-tau-tau red\. coupling\^2'),
          comment=''),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="a1bbrc2", type=float,
          regex=re.compile(r' +[E\d\.\-\+]+ +([E\d\.\-\+]+) +3 +36 +5 +5 \# CP-odd Higgs\(1\)-b-b red\. coupling\^2'),
          comment=''),

    # Higgs branching ratios
    # h1
    Field(block='DCINFO', name="Brh1gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_1 \-> gluon gluon\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1mumu", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +13 +\-13 +\# BR\(H_1 \-> muon muon\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_1 \-> tau tau\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1cc", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +4 +\-4 +\# BR\(H_1 \-> c cbar\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_1 \-> b bbar\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_1 \-> W\+ W\-\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_1 \-> Z Z\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_1 \-> gamma gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_1 \-> Z gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_1 \-> A_1 A_1\)'),
          comment=''),
    Field(block='DCINFO', name="Brh1a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_1 \-> A_1 Z\)'),
          comment=''),

    # h2
    Field(block='DCINFO', name="Brh2gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_2 \-> gluon gluon\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_2 \-> tau tau\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_2 \-> b bbar\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_2 \-> W\+ W\-\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_2 \-> Z Z\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_2 \-> gamma gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_2 \-> Z gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_2 \-> A_1 A_1\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_2 \-> A_1 Z\)'),
          comment=''),
    Field(block='DCINFO', name="Brh2h1h1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +25 +\# BR\(H_2 \-> H_1 H_1\)'),
          comment=''),

    # h3
    Field(block='DCINFO', name="Brh3gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_3 \-> gluon gluon\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_3 \-> tau tau\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_3 \-> b bbar\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_3 \-> W\+ W\-\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_3 \-> Z Z\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_3 \-> gamma gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_3 \-> Z gamma\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_3 \-> A_1 A_1\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_3 \-> A_1 Z\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3h1h1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +25 +\# BR\(H_3 \-> H_1 H_1\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3h2h2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +35 +35 +\# BR\(H_3 \-> H_2 H_2\)'),
          comment=''),
    Field(block='DCINFO', name="Brh3h1h2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +35 +\# BR\(H_3 \-> H_1 H_2\)'),
          comment=''),

    # a1
    Field(block='DCINFO', name="Bra1mumu", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +13 +\-13 +\# BR\(A_1 \-> muon muon\)'),
          comment=''),
    Field(block='DCINFO', name="Bra1tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(A_1 \-> tau tau\)'),
          comment=''),
    Field(block='DCINFO', name="Bra1bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(A_1 \-> b bbar\)'),
          comment=''),
    Field(block='DCINFO', name="Bra1gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(A_1 \-> gluon gluon\)'),
          comment=''),
    Field(block='DCINFO', name="Bra1cc", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +4 +\-4 +\# BR\(A_1 \-> c cbar\)'),
          comment=''),
    Field(block='DCINFO', name="Bra1ss", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +3 +\-3 +\# BR\(A_1 \-> s sbar\)'),
          comment='')
]