"""Declare all the fields & associated regexes you want for pulling info from NMSSMTools spectrum file"""


from collections import namedtuple
import re


Field = namedtuple('Field', ['block', 'regex', 'name', 'type'])

nmssmtools_fields = [
    # parameters
    Field(block='MINPAR', name="tgbeta", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# TANBETA\(MZ\)')),
    Field(block='EXTPAR', name="mueff", type=float,
          regex=re.compile(r' +65 +([E\d\.\-\+]+) +\# MUEFF')),
    Field(block='EXTPAR', name="lambda", type=float,
          regex=re.compile(r' +61 +([E\d\.\-\+]+) +\# LAMBDA')),
    Field(block='EXTPAR', name="kappa", type=float,
          regex=re.compile(r' +62 +([E\d\.\-\+]+) +\# KAPPA')),
    Field(block='EXTPAR', name="alambda", type=float,
          regex=re.compile(r' +63 +([E\d\.\-\+]+) +\# ALAMBDA')),
    Field(block='EXTPAR', name="akappa", type=float,
          regex=re.compile(r' +64 +([E\d\.\-\+]+) +\# AKAPPA')),

    # Field(block='EXTPAR', name="m0", type=float,
    #       regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# M0\(MGUT\)')),
    # Field(block='EXTPAR', name="m12", type=float,
    #       regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# M12\(MGUT\)')),
    # Field(block='EXTPAR', name="a0", type=float,
    #       regex=re.compile(r' +5 +([E\d\.\-\+]+) +\# A0\(MGUT\)')),
    Field(block='EXTPAR', name="m3", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# M3')),
    Field(block='EXTPAR', name="m2", type=float,
          regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# M2')),
    Field(block='EXTPAR', name="m1", type=float,
          regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# M1')),

    Field(block='EXTPAR', name="mu3", type=float,
          regex=re.compile(r' +46 +([E\d\.\-\+]+) +\# RIGHT T-SQUARKS')),
    Field(block='EXTPAR', name="mu2", type=float,
          regex=re.compile(r' +45 +([E\d\.\-\+]+) +\# RIGHT C-SQUARKS')),

    Field(block='EXTPAR', name="mq3", type=float,
          regex=re.compile(r' +43 +([E\d\.\-\+]+) +\# LEFT 3RD GEN. SQUARKS')),
    Field(block='EXTPAR', name="mq2", type=float,
          regex=re.compile(r' +42 +([E\d\.\-\+]+) +\# LEFT 2ND GEN. SQUARKS')),

    Field(block='EXTPAR', name="au3", type=float,
          regex=re.compile(r' +11 +([E\d\.\-\+]+) +\# ATOP')),
    Field(block='EXTPAR', name="ad3", type=float,
          regex=re.compile(r' +12 +([E\d\.\-\+]+) +\# ABOTTOM')),

    Field(block='EXTPAR', name="ml3", type=float,
          regex=re.compile(r' +33 +([E\d\.\-\+]+) +\# LEFT STAU')),
    Field(block='EXTPAR', name="ml2", type=float,
          regex=re.compile(r' +32 +([E\d\.\-\+]+) +\# LEFT SMUON')),

    Field(block='EXTPAR', name="me3", type=float,
          regex=re.compile(r' +36 +([E\d\.\-\+]+) +\# RIGHT STAU')),
    Field(block='EXTPAR', name="me2", type=float,
          regex=re.compile(r' +35 +([E\d\.\-\+]+) +\# RIGHT SMUON')),

    Field(block='EXTPAR', name="ae3", type=float,
          regex=re.compile(r' +13 +([E\d\.\-\+]+) +\# ATAU')),
    Field(block='EXTPAR', name="ae2", type=float,
          regex=re.compile(r' +16 +([E\d\.\-\+]+) +\# AMUON')),

    Field(block='EXTPAR', name="md3", type=float,
          regex=re.compile(r' +49 +([E\d\.\-\+]+) +\# RIGHT B-SQUARKS')),
    Field(block='EXTPAR', name="md2", type=float,
          regex=re.compile(r' +48 +([E\d\.\-\+]+) +\# RIGHT S-SQUARKS')),

    # masses
    Field(block='MASS', name="mh1", type=float,
          regex=re.compile(r' +25 +([E\d\.\-\+]+) +\# lightest neutral scalar')),
    Field(block='MASS', name="mh2", type=float,
          regex=re.compile(r' +35 +([E\d\.\-\+]+) +\# second neutral scalar')),
    Field(block='MASS', name="mh3", type=float,
          regex=re.compile(r' +45 +([E\d\.\-\+]+) +\# third neutral scalar')),
    Field(block='MASS', name="ma1", type=float,
          regex=re.compile(r' +36 +([E\d\.\-\+]+) +\# lightest pseudoscalar')),
    Field(block='MASS', name="ma2", type=float,
          regex=re.compile(r' +46 +([E\d\.\-\+]+) +\# second pseudoscalar')),
    Field(block='MASS', name="mhc", type=float,
          regex=re.compile(r' +37 +([E\d\.\-\+]+) +\# charged Higgs')),
    Field(block='MASS', name="mstop1", type=float,
          regex=re.compile(r'   1000006 +([E\d\.\-\+]+) +#  ~t_1')),
    Field(block='MASS', name="mstop2", type=float,
          regex=re.compile(r'   2000006 +([E\d\.\-\+]+) +#  ~t_2')),
    Field(block='MASS', name="msbottom1", type=float,
          regex=re.compile(r'   1000005 +([E\d\.\-\+]+) +#  ~b_1')),
    Field(block='MASS', name="msbottom2", type=float,
          regex=re.compile(r'   2000005 +([E\d\.\-\+]+) +#  ~b_2')),
    Field(block='MASS', name="mgluino", type=float,
          regex=re.compile(r'   1000021 +([E\d\.\-\+]+) +#  ~g')),
    Field(block='MASS', name="mneutralino1", type=float,
          regex=re.compile(r'   1000022 +([E\d\.\-\+]+) +# neutralino\(1\)')),
    Field(block='MASS', name="mneutralino2", type=float,
          regex=re.compile(r'   1000023 +([E\d\.\-\+]+) +# neutralino\(2\)')),
    Field(block='MASS', name="mchargino1", type=float,
          regex=re.compile(r'   1000024 +([E\d\.\-\+]+) +# chargino\(1\)')),

    # Higgs branching ratios
    # h1
    Field(block='DCINFO', name="Brh1gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_1 \-> gluon gluon\)')),
    Field(block='DCINFO', name="Brh1mumu", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +13 +\-13 +\# BR\(H_1 \-> muon muon\)')),
    Field(block='DCINFO', name="Brh1tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_1 \-> tau tau\)')),
    Field(block='DCINFO', name="Brh1cc", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +4 +\-4 +\# BR\(H_1 \-> c cbar\)')),
    Field(block='DCINFO', name="Brh1bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_1 \-> b bbar\)')),
    Field(block='DCINFO', name="Brh1ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_1 \-> W\+ W\-\)')),
    Field(block='DCINFO', name="Brh1zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_1 \-> Z Z\)')),
    Field(block='DCINFO', name="Brh1gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_1 \-> gamma gamma\)')),
    Field(block='DCINFO', name="Brh1zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_1 \-> Z gamma\)')),
    Field(block='DCINFO', name="Brh1a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_1 \-> A_1 A_1\)')),
    Field(block='DCINFO', name="Brh1a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_1 \-> A_1 Z\)')),

    # h2
    Field(block='DCINFO', name="Brh2gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_2 \-> gluon gluon\)')),
    Field(block='DCINFO', name="Brh2tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_2 \-> tau tau\)')),
    Field(block='DCINFO', name="Brh2bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_2 \-> b bbar\)')),
    Field(block='DCINFO', name="Brh2ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_2 \-> W\+ W\-\)')),
    Field(block='DCINFO', name="Brh2zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_2 \-> Z Z\)')),
    Field(block='DCINFO', name="Brh2gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_2 \-> gamma gamma\)')),
    Field(block='DCINFO', name="Brh2zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_2 \-> Z gamma\)')),
    Field(block='DCINFO', name="Brh2a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_2 \-> A_1 A_1\)')),
    Field(block='DCINFO', name="Brh2a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_2 \-> A_1 Z\)')),
    Field(block='DCINFO', name="Brh2h1h1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +25 +\# BR\(H_2 \-> H_1 H_1\)')),

    # h3
    Field(block='DCINFO', name="Brh3gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(H_3 \-> gluon gluon\)')),
    Field(block='DCINFO', name="Brh3tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(H_3 \-> tau tau\)')),
    Field(block='DCINFO', name="Brh3bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(H_3 \-> b bbar\)')),
    Field(block='DCINFO', name="Brh3ww", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +24 +\-24 +\# BR\(H_3 \-> W\+ W\-\)')),
    Field(block='DCINFO', name="Brh3zz", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +23 +\# BR\(H_3 \-> Z Z\)')),
    Field(block='DCINFO', name="Brh3gammagamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +22 +22 +\# BR\(H_3 \-> gamma gamma\)')),
    Field(block='DCINFO', name="Brh3zgamma", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +22 +\# BR\(H_3 \-> Z gamma\)')),
    Field(block='DCINFO', name="Brh3a1a1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +36 +36 +\# BR\(H_3 \-> A_1 A_1\)')),
    Field(block='DCINFO', name="Brh3a1z", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +23 +36 +\# BR\(H_3 \-> A_1 Z\)')),
    Field(block='DCINFO', name="Brh3h1h1", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +25 +\# BR\(H_3 \-> H_1 H_1\)')),
    Field(block='DCINFO', name="Brh3h2h2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +35 +35 +\# BR\(H_3 \-> H_2 H_2\)')),
    Field(block='DCINFO', name="Brh3h1h2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +25 +35 +\# BR\(H_3 \-> H_1 H_2\)')),

    # a1
    Field(block='DCINFO', name="Bra1mumu", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +13 +\-13 +\# BR\(A_1 \-> muon muon\)')),
    Field(block='DCINFO', name="Bra1tautau", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +15 +\-15 +\# BR\(A_1 \-> tau tau\)')),
    Field(block='DCINFO', name="Bra1bb", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +5 +\-5 +\# BR\(A_1 \-> b bbar\)')),
    Field(block='DCINFO', name="Bra1gg", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +21 +21 +\# BR\(A_1 \-> gluon gluon\)')),
    Field(block='DCINFO', name="Bra1cc", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +4 +\-4 +\# BR\(A_1 \-> c cbar\)')),
    Field(block='DCINFO', name="Bra1ss", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +2 +3 +\-3 +\# BR\(A_1 \-> s sbar\)')),

    # Reduced Higgs Couplings Bosons
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h1ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +25 +21 +21 \# Higgs\(1\)-gluon-gluon reduced coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h1bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +25 +5 +5 \# Higgs\(1\)-b-b red\. coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h1vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +25 +24 +24 \# Higgs\(1\)-W-W reduced coupling\^2')),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h2ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +35 +21 +21 \# Higgs\(2\)-gluon-gluon reduced coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h2bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +35 +5 +5 \# Higgs\(2\)-b-b red\. coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h2vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +35 +24 +24 \# Higgs\(2\)-W-W reduced coupling\^2')),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h3ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +45 +21 +21 \# Higgs\(3\)-gluon-gluon reduced coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="h3bbrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +[E\d\.\-\+]+ +3 +45 +5 +5 \# Higgs\(3\)-b-b red\. coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="h3vvrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +45 +24 +24 \# Higgs\(3\)-W-W reduced coupling\^2')),

    Field(block='HiggsBoundsInputHiggsCouplingsBosons', name="a1ggrc2", type=float,
          regex=re.compile(r' +([E\d\.\-\+]+) +3 +36 +21 +21 \# CP-odd Higgs\(1\)-gluon-gluon reduced coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="a1tautaurc2", type=float,
          regex=re.compile(r' +[E\d\.\-\+]+ +([E\d\.\-\+]+) +3 +36 +15 +15 \# CP-odd Higgs\(1\)-tau-tau red\. coupling\^2')),
    Field(block='HiggsBoundsInputHiggsCouplingsFermions', name="a1bbrc2", type=float,
          regex=re.compile(r' +[E\d\.\-\+]+ +([E\d\.\-\+]+) +3 +36 +5 +5 \# CP-odd Higgs\(1\)-b-b red\. coupling\^2')),

    # Flavour observeables
    Field(block="LOWEN", name="bsgamma", type=float,
          regex=re.compile(r' +1 +([E\d\.\-\+]+) +\# BR\(b \-> s gamma\)')),
    Field(block="LOWEN", name="delmd", type=float,
          regex=re.compile(r' +2 +([E\d\.\-\+]+) +\# Delta M_d in ps\^\-1')),
    Field(block="LOWEN", name="delms", type=float,
          regex=re.compile(r' +3 +([E\d\.\-\+]+) +\# Delta M_s in ps\^\-1')),
    Field(block="LOWEN", name="bsmumu", type=float,
          regex=re.compile(r' +4 +([E\d\.\-\+]+) +\# BR\(Bs \-> mu\+mu\-\)')),
    Field(block="LOWEN", name="btaunu", type=float,
          regex=re.compile(r' +5 +([E\d\.\-\+]+) +\# BR\(B\+ \-> tau\+ \+ nu_tau\)')),
    # g-2
    Field(block='LOWEN', name="Del_a_mu", type=float,
          regex=re.compile(r' +6 +([E\d\.\-\+]+) +\# Del_a_mu')),
    Field(block='LOWEN', name="omega", type=float,
          regex=re.compile(r' +10 +([E\d\.\-\+]+) +\# Omega h\^2')),
    # b ->c tau nu
    Field(block='LOWEN', name="rd", type=float,
          regex=re.compile(r'# +([E\d\.\-\+]+) +RD')),
    Field(block='LOWEN', name="rds", type=float,
          regex=re.compile(r'# +([E\d\.\-\+]+) +RD\*')),

    # HiggsBounds results
    Field(block='HiggsBoundsResults', name="HBresult", type=float,
          regex=re.compile(r' +\d +\d +([01\-]) +\# HBresult')),
    Field(block='HiggsBoundsResults', name="HBobsratio", type=float,
          regex=re.compile(r' +\d +\d +([E\d\.\-\+]+) +\# obsratio')),
    Field(block='HiggsBoundsResults', name="HBchannel", type=float,
          regex=re.compile(r' +\d +\d +([E\d\.\-\+]+) +\# channel id number')),

    # Higgssignals results
    Field(block='HiggsSignalsResults', name='HSprob', type=float,
          regex=re.compile(r' +13 +([E\d\.\-\+]+) +\# Probability ')),
    Field(block='HiggsSignalsResults', name='HSchi2', type=float,
          regex=re.compile(r' +12 +([E\d\.\-\+]+) +\# chi\^2 \(total\)')),
    Field(block='HiggsSignalsResults', name='HSnobs', type=int,
          regex=re.compile(r' +7 +([E\d\.\-\+]+) +\# Number of observables \(total\)')),
]